### ISSUE TITLE
Fix schema parents for real

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#478] opened 2017-10-20 20:15 UTC
Undo https://github.com/PolymerLabs/arcs/pull/476 and fix upstream

**Comment by seefeldb** [comment] 2017-10-25 17:55
Repro steps:
 - undo patch
 - build cdn and run server
 - open http://localhost/arcs-cdn/dev/apps/web/?amkey=-KxJeJdSDXjPMapvlDaf
 - switch to user Smitty
 - see error in console

To recreate the situation:
 - in new arc, search for "food" tap "select <user's> favorite food"
 - tap the little person icon, which marks this as a profile arc
 - in new arc, search for "restaurants"
Now, the strategizer finds a suggestion to "Check for <user's> favorite food: Bacon" and while speculatively running it creates an error.

**Comment by shans** [comment] 2017-10-25 21:36
I've managed to repro, and traced it back to the shared-arcs stuff. Specifically, it looks like there's an out-of-date schema stored in firebase somewhere for 'FavoriteFood'.

This is going to be a recurring problem as we make changes to data representations in the core; is there a convenient way to flush out demo data & recreate with an up-to-date core?

**Comment by seefeldb** [comment] 2017-10-25 21:50
Huh, I just created the other arc with favorite food this morning at
http://localhost/arcs-cdn/dev/apps/web/?amkey=-KxJe2wVXWUZClM0ktNL

So maybe it's inflated incorrectly, not out-of-date? You mentioned that schema.parents should always be at least [], set somewhere upstream.

(and yes, we have a "privatize all" button, which essentially does that. and scott moved everything in firebase into 0.2, so that we can just increase that whenever we feel there is an incompatible change and/or we want to freeze a stable state. we'd never share arcs across those versions).

**Comment by noelutz** [comment] 2017-10-27 19:31
@shans there is a way to do a flush as you describe: https://screenshot.googleplex.com/NYE4H2Pho4x

Found the problem. The storage shell is serializing the type into Firebase and then parsing it back and passing it to the Type constructor. The problem is that Firebase drops empty arrays and fields.

Fixed the code to lookup schemas in the context where possible. I think that should fix the bug. I don't see any exceptions anymore.

**Comment by noelutz** [comment] 2017-10-27 19:32
@shans should I move that getRealType function to manifest.js? E.g., findType()?

**Comment by shans** [comment] 2017-10-28 03:18
@noelutz type.js has a static fromLiteral() which should do what you want - instead of searching in the schema for a type in might be better just to manually "put back" empty fields before doing that..

.. which is making me start to think that we should adopt Berni's original fix, at least while we're dealing with storage engines that elide values.

**Comment by noelutz** [comment] 2017-11-01 01:14
Putting back fields might work but it's a bit brittle. Berni suggested storing the type as string rather than json in Firebase for now given that we're not going to query over these fields anytime soon. We're talking about doing that just for the type information for every view. That should fix the problem and allow the code to call fromLiteral again. I think Scott is refactoring the storage code anyways and is going to take care of that.

**Comment by sjmiles** [comment] 2018-07-17 18:29
Old and has lost relevancy, closing.

**Closed by sjmiles** 2018-07-17 18:29 UTC
