### ISSUE TITLE
Create a canonical Arcs on-disk Repo structure

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2809] opened 2019-03-27 19:45 UTC
As part of the ingest design it's become clear that we need to have a well-documented and consistent structure for on-disk artifacts when running Arcs in a server environment.

The pain points come from:
- Current server is in-memory and doesn't everything goes away on restart. (Makes testing hard)
- On disk support is available in cloud deployment, but it is not being tested.
- We need to really think about versioning and how the system as a whole can work well with new versions  of Runtime.

To that end I propose that we support an on-disk format for the Arcs Repo, and a set of commands to manage it.  To make things easy for developers and administrators we should consider mimicing existing repo systems like git.

The on disk repo might look something like this:
```
   .arcs/
      config.json
          {"version": 1,
            ...
          }
      db/

**Comment by shaper** [comment] 2019-05-08 17:26
Looks like an early duplicate of https://github.com/PolymerLabs/arcs/issues/2810

**Closed by shaper** 2019-05-08 17:26 UTC
