### ISSUE TITLE
Errors when initializing a pouchdb local store

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2679] opened 2019-02-08 19:16 UTC
Repro: run web-shell with an uninitialized pouch database url (aka `blarn` below)

`/web-shell/?log=&plannerStorage=volatile&storage=pouchdb://local/blarn`

Get these warnings/exceptions:

![image](https://user-images.githubusercontent.com/98045/52500367-aa117080-2b92-11e9-8291-046951ecac2b.png)

Note that refreshing the page produces a working app with no immediate errors.

**Comment by lindner** [comment] 2019-02-08 19:24
Looking into this.  Thanks!

**Comment by lindner** [comment] 2019-02-12 23:04
Still having problems reproducing.

**Comment by sjmiles** [comment] 2019-02-14 03:17
Video demonstration here https://drive.google.com/open?id=1y9WxlWq9dW6qOId-y49Nb-z1kRefI0dX

I could reproduce this on live 3 for 3 tries, link like so:

https://polymerlabs.github.io/arcs-live/shells/web-shell/?log=&plannerStorage=volatile&storage=pouchdb://local/foop

Remember that the storage DB has to be virginal (aka `foop` must not already exist).

**Comment by sjmiles** [comment] 2019-02-28 00:23
No longer reproducing, calling it good.

**Comment by sjmiles** [comment] 2019-02-28 00:42
Doh, it's still happening, just not every time. :(

**Comment by sjmiles** [comment] 2019-02-28 00:45
Shell creates the Launcher Arc (if it doesn't already exist) and then it observers the arc-metadata collection inside that Arc. 

When the error occurs `store.toList()` returns `[null]` which is what the console calls _malformed_ because the Array should always contain Entity data (never nulls).

A short time later, that `store.toList()` works well. Perhaps something is not properly awaited?

**Comment by sjmiles** [comment] 2019-03-06 00:19
I am seeing what I think is the same error when reloading an Arc.

![image](https://user-images.githubusercontent.com/98045/53846572-48aaaa80-3f62-11e9-918a-88482d6a4479.png)

Repro steps:
1. start from launcher
2. choose 'Find Restaurants'
3. wait for arc to stabilize
4. refresh

**Comment by shaper** [comment] 2019-03-19 20:51
This is my top issue to look at. I expect to have time Wed/Thu this week to look.

**Comment by shaper** [comment] 2019-03-26 21:33
Summary: I can repro the first-load-new-user case, but with a different error than previously. I can repro the restaurant load error and it looks like a Pouch Collection load issue, or some mismatch between the collection's storage type (volatile) vs the backing store implementation (PouchDB).

More detail:

Attempting to repro with earlier notes, a never before referenced user, visiting web shell via say http://localhost:9119/shells/web-shell/index.html?log=&plannerStorage=volatile&storage=pouchdb://local/bax I see a different error 100% of the time as below, it looks like initially we try to load the user's context and perhaps the act of doing that fails to marshal a store:

```
ArcHost instantiateDefaultRecipe
user-context.js:71 UserContext failed to marshal arcsStore for [user][pouchdb://local/bax]
fetchArcsStore @ user-context.js:71
xen-debug.js:22
```

and then later we see (and break into debugger):

```
Uncaught (in promise) TypeError: Cannot read property 'rawData' of null
    at single-user-context.js:42
    at Array.forEach (<anonymous>)
    at single-user-context.js:42
    at SingleUserContext.observeStore (single-user-context.js:109)
```

the value there is:

```
SingleUserContext arcstore::observer 
{add: Array(1)}
add: Array(1)
0:
value: null
```

Reloading produces app load with no console errors/warnings, so it's an initial-load/read/write flow issue as was noted in original issue description. But the errors read quite different now than before. The underlying symptom could be the same (Pouch storage adapter treating certain events/reads/writes differently from Firebase), perhaps other code has changed around it producing differing errors.

Attempting to follow the Restaurants repro I get an error on reload in planner speculative execution in `volatile-storage.ts` in `cloneFrom` [here](https://github.com/PolymerLabs/arcs/blob/master/src/runtime/storage/volatile-storage.ts#L221) where it has a null `underlying`. This looks like it's something in `PouchDbCollection.getMultiple` which must be returning `null` in a case where it should never do so. The `this.storageKey` in `VolatileCollection.cloneFrom` is `"volatile://!53838425003052:user--LavtCtYqzgffKTgb8Lx:9^^volatile-2"` but the `handle.backingStore` type is `PouchDbCollection`. This seems wrong to me, shouldn't the class type match the backing store adapter, but this code has changed quite a bit since I looked at it list.

**Comment by shaper** [comment] 2019-03-26 21:58
Not sure yet whether it's related, but documenting some research findings. The on-first-load is hitting at least two TODOs in the PouchDbCollection code:

1. [`modelForSynchronization`](https://github.com/PolymerLabs/arcs/blob/master/src/runtime/storage/pouchdb/pouch-db-collection.ts#L88) re: `should this change for reference mode??`` (and I confirmed that the store involved is a reference mode store)
2. [`getModel`](https://github.com/PolymerLabs/arcs/blob/master/src/runtime/storage/pouchdb/pouch-db-collection.ts#L307) re: firing change events

These first hit immediately following the shell executing:

`ArcHost persisting serialization to [user-launcher/serialization]`

The store involved is:

```
this
PouchDbCollection {referenceMode: true, _type: CollectionType, listeners: Map(1), name: null, version: 0, …}backingStore: nullid: "!160296378925121:user-launcher:1"listeners: Map(1) {"Change" => Map(2)}name: nullnextLocalID: 0pendingBackingStore: nullpouchDbKey: PouchDbKey {protocol: "pouchdb", dbLocation: "local", dbName: "abcdefg", location: "user-launcher/handles/!160296378925121:user-launcher:1"}referenceMode: truesource: nullstorageEngine: PouchDbStorage {arcId: Id, _debug: false, providerByLocationCache: Map(1), baseStores: Map(0), baseStorePromises: Map(0)}version: 0_model: CrdtCollectionModel {items: Map(0)}_rev: undefined_storageKey: "pouchdb://local/abcdefg/user-launcher/handles/!160296378925121:user-launcher:1"_type: CollectionType {tag: "Collection", collectionType: EntityType}apiChannelMappingId: (...)db: (...)storageKey: (...)type: (...)__proto__: PouchDbStorageProvider
this.toString()
"store of [ArcMeta {Text description, Text icon, Text key, Text href, Text bg, Text color, Text profile, Text blurb, Number share, Number touched, Boolean deleted, Boolean starred, URL externalManifest}] '!160296378925121:user-launcher:1'"
```

**Comment by shaper** [comment] 2019-03-26 22:43
I chatted briefly with @shans and the storage refactor work which will affect existing reference mode logic is getting underway again. I will spend a bit more time here but likely it will make sense to wait for that. I'll partner with him on the Pouch specific implementation.

**Comment by shaper** [comment] 2019-04-01 18:14
Focusing just on the first-load for a user issue, `SingleUserContext.observeStore` ends up in `PouchDbCollection._toList` and the single item we get via `(await this.getModel()).toLiteral()` has more info than what we get when we subsequently call `await this.ensureBackingStore()` and then retrieve the item via `this.backingStore.get(ref.id)`.

I'm still learning current Shell Launcher Arc logic and the existing Pouch and reference mode implementation but this mismatch seems incorrect and ends up returning a `null` value which is what then causes Shell logic to throw an exception as `Uncaught (in promise) TypeError: Cannot read property 'rawData' of null at single-user-context.js:42`

The PouchDBCollection info is as:

```
pouchDbKey: PouchDbKey
dbLocation: "local"
dbName: "abcdefghij"
location: "user-launcher/handles/!473989514631860:user-launcher:1"
```

The value in the model is:

```
id: "user-null"
keys: ["-LbP1zjNrybb3CM7Ht45"]
value:
  id: "user-null"
  storageKey: "pouchdb://local/abcdefghij/backingStores/ArcMeta {Text description, Text icon, Text key, Text href, Text bg, Text color, Text profile, Text blurb, Number share, Number touched, Boolean deleted, Boolean starred, URL externalManifest}"
```

The value we get when we fetch from the backing store is:

```
id: "user-null"
keys: ["-LbP1zjNrybb3CM7Ht45"]
value: null
```

**Comment by sjmiles** [comment] 2019-04-01 19:14
Thanks a million for diving in, @shaper 

I believe it's true that we should never have a `null` Entity. If that's true, maybe we can assert that somewhere, because otherwise I suspect this basic problem shows up as different kinds of errors downstream.

> user-context.js:71 UserContext failed to marshal arcsStore for [user][pouchdb://local/bax]
fetchArcsStore @ user-context.js:71

As of now, this is normal unless it comes up continually (as it does if you use `storage=volatile://`). I'll make it less noisy and/or see about fixing it completely.

**Comment by lindner** [comment] 2019-04-05 00:14
This should be fixed now.  Amazing that some of this code worked at all beforehand.

**Closed** 2019-04-08 18:25 UTC
Labels: p1
