### ISSUE TITLE
Suggestion would perform duplicate work

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2545] opened 2019-01-08 21:18 UTC
A Pipe request creates an arc with an activeRecipe like this:
```
recipe TVMazeShowPipe
  use 'LivePipeEntity' #pipe_entity as handle0 // PipeEntity {...}
  use '!421392602208076:scott-piped--LVjBq2Bdkr75vO_8ryH:6' as handle1 // [Description {...}]
  use '!421392602208076:scott-piped--LVjBq2Bdkr75vO_8ryH:7' as handle2 // TVMazeFind {...}
  use '!421392602208076:scott-piped--LVjBq2Bdkr75vO_8ryH:8' #piped #tv_show as handle3 // TVMazeShow {...}
  slot 'slotid-!421392602208076:scott-piped--LVjBq2Bdkr75vO_8ryH:1' as slot0
  slot 'slotid-!421392602208076:scott-piped--LVjBq2Bdkr75vO_8ryH:5' as slot1
  slot 'rootslotid-root' #root as slot2
  PipeEntityReceiver as particle0
    pipe <- handle0
    consume root as slot2
      provide pipes as slot0
  TVMazeFindPipeShow as particle1
    descriptions -> handle1
    find <- handle2
    show -> handle3
  TVMazeShowPipe as particle2
    find -> handle2
    pipe <- handle0
    consume pipes as slot0
      provide content as slot1
```

Then the planner suggests adding particles like so:

```
recipe TVMazeShowPipe
  create as handle0 // [~a]
  create as handle1 // TVMazeFind {...}
  create #piped #tv_show as handle2 // ~
  use 'LivePipeEntity' as handle3 // PipeEntity {...}
  slot 'slotid-!421392602208076:scott-piped--LVjBq2Bdkr75vO_8ryH:1' as slot0
  TVMazeFindPipeShow as particle0
    descriptions -> handle0
    find <- handle1
    show -> handle2
  TVMazeShowPipe as particle1
    find -> handle1
    pipe <- handle3
    consume pipes as slot0
      provide content as slot1
```

The suggestion will work fine, but all it does is create a duplicate handle (`create #piped #tv_show as handle2`) and recalculate data that already exists in the Arc.

**Comment by mmandlis** [comment] 2019-01-08 22:49
I think this is duplicate of https://github.com/PolymerLabs/arcs/issues/2491

**Comment by shaper** [comment] 2019-02-27 21:23
Duplicate of #2491

**Closed by shaper** 2019-02-27 21:23 UTC
